services:
  gha-cache-server:
    image: ghcr.io/n-cloud-labs/gha-cache-server:latest
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      PORT: 8080
      RUST_LOG: info,github_actions_cache_rs=info
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/cache
      BLOB_STORE: s3
      S3_BUCKET: cache
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_REGION: us-east-1
      AWS_ENDPOINT_URL: http://minio:9000
      S3_FORCE_PATH_STYLE: "true"
      ENABLE_DIRECT_DOWNLOADS: "true"
    ports:
      - "8080:8080"

  postgres:
    image: ghcr.io/bitcompat/postgresql:16
    environment:
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_USER: postgres
      POSTGRESQL_DB: cache
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cache"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./_data/minio:/data
