apiVersion: v1
kind: Service
metadata:
  name: {{ include "gha-cache-server.fullname" . }}
  labels:
    {{- include "gha-cache-server.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ipFamilyPolicy: {{ .Values.service.familyPolicy }}
  ipFamilies: {{ .Values.service.ipFamilies|toJson }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "gha-cache-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
