name: Clippy

on:
  push:
    branches:
      - main
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - 'Cargo.lock'

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  RUSTC_WRAPPER: sccache
  SCCACHE_GHA_ENABLED: 'true'
  SCCACHE_GHA_VERSION: '1-amd64'

jobs:
  check-clippy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Install Rust toolchain
        run: |-
          command -v rustup || ( curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --component clippy )
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
      - name: Update Rust toolchain
        run: rustup update
      - name: Install protobuf compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
