name: Clippy

on:
  push:
    branches:
      - main
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - 'Cargo.lock'

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check-clippy:
    runs-on: self-hosted
    services:
      postgres:
        image: ghcr.io/bitcompat/postgresql:17
        env:
          POSTGRESQL_USERNAME: nimbus
          POSTGRESQL_PASSWORD: secret
          POSTGRESQL_DATABASE: cache
          ALLOW_EMPTY_PASSWORD: 'yes'
        options: >-
          --health-cmd="pg_isready -U nimbus" --health-interval=10s --health-timeout=5s --health-retries=5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust toolchain
        run: |-
          command -v rustup || ( curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --component clippy )
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
      - name: Update Rust toolchain
        run: rustup update
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: 'true'
      - name: Install sqlx-cli
        run: cargo install sqlx-cli
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Setup database
        run: cargo sqlx database setup
        env:
          DATABASE_URL: postgres://nimbus:secret@localhost:5432/cache
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
        env:
          DATABASE_URL: postgres://nimbus:secret@localhost:5432/cache
