name: Clippy

on:
  push:
    branches:
      - main
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - 'Cargo.lock'

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check-clippy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust toolchain
        run: |-
          command -v rustup || ( curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --component clippy )
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
      - name: Update Rust toolchain
        run: rustup update
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: 'true'
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
